"""Initial migration

Revision ID: ec7b56cc7d44
Revises: 
Create Date: 2024-10-25 22:44:14.596617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7b56cc7d44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time_spent',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('color_matrix',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('color_matrix',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('time_spent',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
